### ISSUE TITLE
prevent emojification in code blocks

### ISSUE THREAD

**Issue by cobber** [yuin/goldmark-emoji#3]
I have a table full of MAC addresses, some of them containing e.g. `:de:` which gets translated to 🇩🇪, even though it is surrounded by back-ticks.

e.g.: *(with fake data)*

| What I See        | What I Expect       |
|-------------------|---------------------|
| ab:cd:01:de:ef:02 | `ab:cd:01:de:ef:02` |

I have wrapped all of the data in backticks, but that has no effect on goldmark, but works here on github.

I have not found any way to disable the emojification, e.g. `\:de:` just adds a `\` before the emoji, `:\de:` disables the emoji, but leaves a spurious `\` in my data, killing copy-pastability.

I'm using goldmark v1.4.4 via Hugo v0.93.0

**Comment by yuin** [comment]
goldmark is not dedicated for Hugo.
If you have an issue 'via' Hugo, Please submit issues in Hugo repository.

**Comment by hjtgh** [comment]
The content in backticks should be rendered intact, which seems to be the responsibility of a markdown parser.

**Comment by yuin** [comment]
@Qutue Did you read above issue? (https://github.com/gohugoio/hugo/issues/7332)

This issue is **completely misunderstanding** by @cobber  because Hugo does not use this extension.
Many users misunderstand about Hugo's markdown. goldmark does **NOT** control **ALL** of Hugo's markdown. goldmark is an **extensible** markdown parser. Hugo has many own extensions for goldmark. Hugo has functions for templating that do not have relation with goldmark.

If you meet problems about Hugo and do not have skills to investigate weather cause is Hugo or goldmark, you should submit an issue in Hugo repository.
